---
"on":
  pull_request:
    branches:
      - "**"
    paths:
      - "Dockerfile"
      - .github/workflows/build-runner.yml
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
      - .github/workflows/build-runner.yml

name: Runner
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: actions-runner
            dockerfile: Dockerfile
    env:
      RUNNER_VERSION: 2.274.1
      DOCKER_VERSION: 19.03.13
      DOCKERHUB_USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true

      - name: Build Image
        if: ${{ github.event_name == 'pull_request' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: false
          build-args: |
            RUNNER_VERSION=${RUNNER_VERSION}
            DOCKER_VERSION=${DOCKER_VERSION}

      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        if: ${{ github.event_name == 'push' }}
        id: docker_build_and_push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            RUNNER_VERSION=${RUNNER_VERSION}
            DOCKER_VERSION=${DOCKER_VERSION}
          tags: |
            ${DOCKERHUB_USERNAME}/actions-runner:latest
            ${DOCKERHUB_USERNAME}/actions-runner:v${RUNNER_VERSION}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
